#!/usr/bin/env php
<?php
defined('ROOT_DIR') or define('ROOT_DIR', __DIR__);

require_once ROOT_DIR . '/vendor/autoload.php';

$app = \PhpLab\Application\Factory\App\CliAppFactory::prepare();
$app->run();